name: Different Compare
on: [push]
jobs:
  self_compare:
    name: Different Compare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Run a script
        run: diff file.txt different.txt
